name: Chatops Dispatch
on:
  issue_comment:
    types: [created]
jobs:
  chatop-dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: peter-evans/slash-command-dispatch
          path: ./slash-command-dispatch
          ref: v3
      - uses: ./slash-command-dispatch
        with:
          token: ${{ secrets.PAT }}
          commands: |
            squash-commits-with-message
