name: Squash commits
on:
  repository_dispatch:
      types: [squash-commits-with-message-command]
jobs:
  squash-commits:
    runs-on: ubuntu-latest
    steps:
    - id: determine-commit-message
      run: |
        echo "commit-message=${{ github.event.client_payload.slash_command.args.unnamed.arg1 }}" >> "$GITHUB_OUTPUT"
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.client_payload.pull_request.head.ref }}
    - run: |
        npm i
        npm run lint:commit-message
      env:
        COMMIT_MESSAGE: ${{ steps.determine-commit-message.outputs.commit-message }}

    - run: |
        git config user.name github-actions[bot]
        git config user.email github-actions[bot]@users.noreply.github.com
        git remote add gh-token "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.event.repository.name }}.git"
    - run: |
        git branch --track main origin/main
        git reset --soft $(git merge-base main HEAD)
        git commit -m "${{ steps.determine-commit-message.outputs.commit-message }}"
        git push origin $(git branch --show-current) --force-with-lease

    - if: always()
      uses: actions/checkout@v3
      with:
        repository: peter-evans/create-or-update-comment
        path: ./create-or-update-comment
        ref: v2
    - if: success()
      uses: ./create-or-update-comment
      with:
        repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
        issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
        body: |
          Commits successfully squashed
        reaction-type: hooray
    - if: failure()
      uses: ./create-or-update-comment
      with:
        repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
        issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
        body: |
          Something went wrong during squash
        reaction-type: hooray
